[package]
name = "rust_bencode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha-1 = "0.10.0"
ureq = "2.4.0"
urlencoding = "2.1.0"
rand = "0.8.5"
base32 = "0.4.0"

[profile.bench]
debug = true